#! /bin/bash

git clone https://github.com/popey/unsnap
cd unsnap

./unsnap auto

sudo systemctl disable snapd.service
sudo systemctl disable snapd.socket
sudo systemctl disable snapd.seeded.service

sudo apt autoremove --purge snapd

sudo rm -rf /var/cache/snapd/
rm -rf ~/snap

sudo apt install flatpak

sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak

sudo apt install plasma-discover-flatpak-backend

sudo apt install plasma-discover-backend-flatpak

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
