#! /bin/bash

git clone https://github.com/popey/unsnap
cd unsnap

./unsnap auto

sudo apt install flatpak

sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak

sudo apt install plasma-discover-flatpak-backend

sudo apt install plasma-discover-backend-flatpak

flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
